import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { SubmittedReport, submitReport } from "./api/reports";
import { Navigation } from "./Navigation";
import { OperatorConsole } from "./Operator";
import { MyReports, ReportDetailPage } from "./Tracking";

const allowedTypes = ["image/jpeg", "image/png", "image/webp"];
const maxBytes = 10 * 1024 * 1024;
const statusLabel: Record<string, string> = { submitted: "Report received", analyzed: "Report reviewed", assigned: "Dispatched to repair crew", in_progress: "Repair in progress", resolved: "Road repaired" };
const title = (value: string | null) => value ? value[0].toUpperCase() + value.slice(1) : "Pending";
type LocationState = "idle" | "loading" | "success" | "denied" | "unavailable";

function MapPicker({ latitude, longitude, onChange }: { latitude: string; longitude: string; onChange: (lat: string, lng: string) => void }) {
  const [locationState, setLocationState] = useState<LocationState>("idle");
  const hasCoordinates = latitude !== "" && longitude !== "";
  const notice = { idle: "This is the location that will be attached to your report.", loading: "Finding your current location...", success: "Location found. Confirm or adjust the coordinates below.", denied: "Location permission was denied. Enter the coordinates manually.", unavailable: "Your location is unavailable. Enter the coordinates manually." }[locationState];
  const locate = () => {
    if (!navigator.geolocation) return setLocationState("unavailable");
    setLocationState("loading");
    navigator.geolocation.getCurrentPosition(
      ({ coords }) => { onChange(coords.latitude.toFixed(6), coords.longitude.toFixed(6)); setLocationState("success"); },
      (error) => setLocationState(error.code === error.PERMISSION_DENIED ? "denied" : "unavailable"),
    );
  };
  return <section className="field-group" aria-labelledby="location-heading"><div className="field-heading"><h2 id="location-heading">2. Confirm location</h2><p>Confirm where you found the pothole.</p></div><button type="button" className="secondary" onClick={locate} disabled={locationState === "loading"}>{locationState === "loading" ? "Finding location..." : "Use current location"}</button><div className="map" role="img" aria-label="Location confirmation"><span className="map-pin" aria-hidden="true" /><strong>{hasCoordinates ? "Location selected" : "No location selected"}</strong><small>{hasCoordinates ? `${latitude}, ${longitude}` : "Use your location or enter coordinates below."}</small></div><p className="location-help" role="status">{notice}</p><div className="coordinates"><label>Latitude<input aria-label="Latitude" inputMode="decimal" type="number" step="any" value={latitude} onChange={(event) => onChange(event.target.value, longitude)} /></label><label>Longitude<input aria-label="Longitude" inputMode="decimal" type="number" step="any" value={longitude} onChange={(event) => onChange(latitude, event.target.value)} /></label></div></section>;
}

function SubmissionResult({ report, onNew }: { report: SubmittedReport; onNew: () => void }) {
  return <main className="shell result"><Navigation active="citizen" /><header><p className="eyebrow">Your report was received</p><h1>Thank you for reporting this pothole.</h1><p>We have created a report and added it to the operational workflow.</p></header><section className="result-card" aria-label="Submitted report details"><p className="report-number">Report #{report.report_id}</p><dl><dt>Issue type</dt><dd>Pothole</dd><dt>Severity</dt><dd>{title(report.incident.severity)}</dd><dt>Priority</dt><dd>{title(report.analysis.analysis.priority_level)}</dd><dt>Current status</dt><dd>{statusLabel[report.incident.status] ?? "Status unavailable"}</dd><dt>Location</dt><dd>{report.incident.latitude.toFixed(5)}, {report.incident.longitude.toFixed(5)}</dd></dl></section><section className="next-steps"><h2>What happens next</h2><p>The report is reviewed, prioritised, and routed to the appropriate repair workflow. You can check its status at any time.</p></section>{report.analysis.duplicate_analysis && <aside className="notice"><strong>A related report may already exist.</strong><br />Your report was still received and will be reviewed.</aside>}<a className="track-link" href={`#/reports/${report.report_id}`}>Track this report</a><button className="secondary full-width" onClick={onNew}>Report another pothole</button></main>;
}

export function App() {
  const [description, setDescription] = useState(""); const [latitude, setLatitude] = useState(""); const [longitude, setLongitude] = useState(""); const [photo, setPhoto] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [report, setReport] = useState<SubmittedReport | null>(null); const [route, setRoute] = useState(() => window.location.hash.slice(1) || "/");
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  useEffect(() => { const update = () => setRoute(window.location.hash.slice(1) || "/"); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, []);
  const removePhoto = () => { if (preview) URL.revokeObjectURL(preview); setPreview(""); setPhoto(null); };
  const selectPhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; setError(""); if (!file) return; if (!allowedTypes.includes(file.type)) return setError("Use a JPEG, PNG, or WEBP image."); if (file.size > maxBytes) return setError("Photo must be 10 MB or less."); if (preview) URL.revokeObjectURL(preview); setPhoto(file); setPreview(URL.createObjectURL(file)); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (!photo) return setError("Add a photo before submitting."); if (description.trim().length < 5) return setError("Describe the pothole in at least 5 characters."); const lat = Number(latitude), lng = Number(longitude); if (!Number.isFinite(lat) || lat < -90 || lat > 90 || !Number.isFinite(lng) || lng < -180 || lng > 180) return setError("Select a valid location before submitting."); setSubmitting(true); try { setReport(await submitReport({ description: description.trim(), latitude: lat, longitude: lng, photo })); } catch (reason) { setError(reason instanceof Error ? reason.message : "We couldn't submit your report. Please try again."); } finally { setSubmitting(false); } };
  if (route === "/reports") return <MyReports openReport={(id) => { window.location.hash = `#/reports/${id}`; }} />;
  if (route === "/operator") return <OperatorConsole />;
  if (route.startsWith("/reports/")) { const reportId = Number(route.split("/")[2]); return Number.isInteger(reportId) && reportId > 0 ? <ReportDetailPage reportId={reportId} /> : <main className="shell"><Navigation active="tracking" /><p className="error" role="alert">Report not found.</p></main>; }
  if (report) return <SubmissionResult report={report} onNew={() => setReport(null)} />;
  return <main className="shell"><Navigation active="citizen" /><header><p className="eyebrow">Pothole reporting</p><h1>Report a pothole</h1><p>Upload a photo, confirm the location, and submit your report for review.</p></header><form onSubmit={submit} noValidate><section className="field-group" aria-labelledby="photo-heading"><div className="field-heading"><h2 id="photo-heading">1. Add photo</h2><p>Take a clear photo that shows the pothole and surrounding road surface.</p></div>{preview ? <div className="preview"><img src={preview} alt="Selected pothole evidence" /><div className="preview-actions"><label className="text-button">Replace photo<input aria-label="Replace photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={selectPhoto} /></label><button type="button" className="text-button" onClick={removePhoto}>Remove photo</button></div></div> : <label className="upload"><input aria-label="Add photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={selectPhoto} /><strong>Upload or take a photo</strong><small>JPEG, PNG, or WEBP. Maximum 10 MB.</small></label>}</section><MapPicker latitude={latitude} longitude={longitude} onChange={(lat, lng) => { setLatitude(lat); setLongitude(lng); }} /><section className="field-group" aria-labelledby="description-heading"><div className="field-heading"><h2 id="description-heading">3. Describe the pothole</h2><p>Include details that may help a repair crew find it.</p></div><label className="sr-only" htmlFor="description">Description</label><textarea id="description" placeholder="For example: Large pothole near the pedestrian crossing" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={1000} /></section>{error && <p className="error" role="alert">{error}</p>}<button className="submit" disabled={submitting}>{submitting ? "Submitting report..." : "Submit report"}</button></form></main>;
}
